### ISSUE TITLE
Make --bbs-server-url, --bbs-project-, and --bbs-repo required arguments for bbs2gh migrate-repo command

### ISSUE THREAD

**Issue by dpmex4527** [github/gh-gei#1004]
This issue tracks followup work to make the `--bbs-server-url`, `--bbs-project`, and `--bbs-repo` arguments required for the bbs2gh `migrate-repo` command (see https://github.com/github/gh-gei/pull/1002#issuecomment-1560511208). This will ensure that we always pass a valid BBS repo URL when starting a migration and we will use it to validate that the archive contains the correct repo data, especially in the use case when customers are migrating forks. This will be a breaking change so we should update our release notes when changes ship.

This issue also covers some cleanup for the now optional `accessToken` GQL field with guidance on changes commented in this review comment https://github.com/github/gh-gei/pull/1002#discussion_r1205769201

## Todo
- [ ] Make `--bbs-server-url`, `--bbs-project`, and `--bbs-repo` arguments for bbs2gh `migrate-repo` command
- [ ] Include breaking change in release notes.
- [ ] Update code to reflect optional `accessToken` gql params

**Comment by timrogers** [comment]
Fixed in https://github.com/github/gh-gei/pull/1057
