### ISSUE TITLE
Update CSV Parsing Logic for Mannequin Reclaimation

### ISSUE THREAD

**Issue by hfishback01** [github/gh-gei#1039]
Currently, our logic in the [ReclaimService.cs](https://github.com/github/gh-gei/blob/main/src/Octoshift/Services/ReclaimService.cs) reads the raw text of the CSV as opposed to using a CSV parsing library. We should update our code to implement a parsing library instead.

We do use [this library](https://learn.microsoft.com/en-us/dotnet/api/microsoft.visualbasic.fileio.textfieldparser?view=net-7.0) in [other places within the CLI](https://github.com/github/gh-gei/blob/main/src/ado2gh/Services/AdoInspectorService.cs#L41).

This is another option worth noting/investigating:

- https://joshclose.github.io/CsvHelper/

## Todo
- [ ] Determine which library to use for CSV parsing
- [ ] Update logic within the ReclaimService to implement the parsing library
- [ ] Add tests as necessary

## Dependencies
- none

**Comment by dylan-smith** [comment]
FYI the 2nd option you have there (learn.microsoft.com) is the same one we're already using in AdoInspectorService.

**Comment by hfishback01** [comment]
> FYI the 2nd option you have there (learn.microsoft.com) is the same one we're already using in AdoInspectorService.

That's what I get for a quick copy and paste! 🙄

**Comment by timrogers** [comment]
Closing in favour of https://github.com/github/gh-gei/issues/969
