### ISSUE TITLE
Enable CLI Integration Tests to be Run Locally

### ISSUE THREAD

**Issue by hfishback01** [github/gh-gei#1049]
Currently, integration tests can only be run in GitHub Actions and are typically observed on push. We should update integration tests so that they easily and successfully run locally to better debug and maintain code.

## Tasks
- [ ] Spike what it would take to update integration tests
- [ ] Update integration tests
- [ ] Update documentation as necessary

## Dependencies
