### ISSUE TITLE
Merge archive command into migrate repo command

### ISSUE THREAD

**Issue by petermeglis** [github/gh-gei#231]
In https://github.com/github/gh-gei/pull/221 we added the migrate archive repo command. Since there's lots of overlap with the current migrate repo command, we should just merge the migrate archive repo command into the migrate repo command and add a flag parameter in order to take the migrate archive route.

## Todo
- [x] Merge the migrate archive repo command into the migrate repo command
- [x] Add a flag to take the migrate archive route
- [x] Add unit tests
- [x] Add unit tests for command parameters

## Dependencies
- https://github.com/github/gh-gei/pull/221
