### ISSUE TITLE
Add AWS region and session token args

### ISSUE THREAD

**Issue by ArinGhazarian** [github/gh-gei#843]
Currently CLI only supports [basic AWS credentials](https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/creds-assign.html) to connect to a AWS S3 bucket. In order to support a wider range of authentication scenarios we need to also support session AWS credentials. Additionally we are going to switch to V4 signature and add AWS region arg. If the AWS region is not specified we are not going to use the V4 signature and will spit out a warning message. 

## Todo
- [x] Add optional `--aws-session-token` arg to `migrate-repo` commands for both gei and bbs2gh.
- [x] Default to signature V4.
- [x] Add (optional for now) `--aws-region` to both `migrate-repo` and `generate-script` commands. 
- [x] If `--aws-region` is not specified, don't use signature V4 and log a warning message that  an AWS region will be required in a future release (let's say from June 1st, giving 3 months). 

## Related
- #744
