### ISSUE TITLE
Dispose HTTP response in BbsClient and AdoClinet

### ISSUE THREAD

**Issue by ArinGhazarian** [github/gh-gei#926]
I noticed that in `BbsClient` and `AdoClient` we are not disposing the HTTP response that is getting returned by the `HttpClient`. The response needs to be immediately disposed with a `using` statement and also all unit tests needs to be fixed the way they were fixed in #925.

## Todo
- [ ] Dispose the http response in `BbsClient#SendAsync()` and `AdoClient#SendAsync()` methods
- [ ] Fix unit tests by using a factory to return a new `HttpResponseMessage` when mocking `HttpMessageHandler` (see #925)
- [ ] _Bonus:_ Simplify `SendAsync` method in both `BbsClient` and `AdoClient` by replacing the switch statement with `HttpClient#SendAsync()` the way it is in `GithubClinet#SendAsync()`.
